import {
  createRunLogEntry,
  getDryRunStageArtifactPaths,
  getPipelineDir,
  getRouteStages,
  makeInitialState,
  makeTelemetryEvent,
  nextStage,
  stageNumber,
} from "../../domain/pipeline";
import type {
  ExecutableRoute,
  FailurePolicy,
  InteractionMode,
  PipelineState,
  TelemetryEvent,
} from "../../domain/pipeline";
import { yamlify } from "../pipeline-state-codec";

export interface RunDryRunInput {
  workspaceRoot: string;
  task: string;
  route: ExecutableRoute;
  interactionMode: InteractionMode;
  failurePolicy: FailurePolicy;
}

export interface RunDryRunPipelinePaths {
  statePath: string;
  telemetryDir: string;
  eventsPath: string;
  runLogPath: string;
  metricsPath: string;
}

export interface RunDryRunDependencies {
  createDirectory(dirPath: string): void;
  writeTextFile(filePath: string, content: string): void;
  resolveWorkspacePath(workspaceRoot: string, filePath: string): string;
  resolveWorkspacePaths(
    workspaceRoot: string,
    runId: string,
  ): RunDryRunPipelinePaths;
  generateRunId(): string;
}

export interface RunDryRunResult {
  runId: string;
  state: PipelineState;
}

function titleCase(value: string): string {
  return value
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("-");
}

function updatePhaseHistory(state: PipelineState, stage: string): void {
  if (stage !== "implement" && stage !== "accept" && stage !== "replan") {
    return;
  }

  const lastEntry = state.phase_history[state.phase_history.length - 1];
  if (!lastEntry || lastEntry.phase !== state.current_phase) {
    state.phase_history.push({
      phase: state.current_phase,
      completed_stages: [stage],
    });
    return;
  }

  if (!lastEntry.completed_stages.includes(stage)) {
    lastEntry.completed_stages.push(stage);
  }
}

function createDryRunArtifactContent(
  runId: string,
  route: ExecutableRoute,
  interactionMode: InteractionMode,
  failurePolicy: FailurePolicy,
  stage: string,
  task: string,
  artifactPath: string,
  stageIndex: number,
  totalStages: number,
): string {
  const relativeArtifactPath = artifactPath.replace(
    `${getPipelineDir(runId)}/`,
    "",
  );
  const heading = `${titleCase(stage)} — Dry Run`;
  const metadata = [
    `- Run ID: ${runId}`,
    `- Mode: dry-run`,
    `- Route: ${route}`,
    `- Interaction Mode: ${interactionMode}`,
    `- Failure Policy: ${failurePolicy}`,
    `- Stage: ${stageNumber(stage)} of ${totalStages} (${titleCase(stage)})`,
    `- Progress: ${stageIndex} of ${totalStages}`,
    `- Artifact: ${relativeArtifactPath}`,
  ].join("\n");

  if (relativeArtifactPath === "requirements.md") {
    return `# Requirements — Dry Run\n\n${task}\n\n---\nThis file was generated by a simulated dry run. No subagents were dispatched and no project files were modified.\n`;
  }

  if (relativeArtifactPath === "config.md") {
    return `# Config — Dry Run\n\n- Run ID: ${runId}\n- Mode: dry-run\n- Route: ${route}\n- Interaction Mode: ${interactionMode}\n- Failure Policy: ${failurePolicy}\n- Selected stages: ${getRouteStages(route).join(", ")}\n`;
  }

  if (relativeArtifactPath === "phase-manifest.md") {
    return `# Phase Manifest — Dry Run\n\n${metadata}\n\n## Phases\n\n- Phase 1 — Simulated implementation phase\n`;
  }

  return `# ${heading}\n\n${metadata}\n\nThis artifact was generated by a simulated dry run. It represents the output shape for this stage without invoking QRSPI subagents or modifying project source files.\n\n## Source Task\n\n${task}\n`;
}

function formatDryRunRunLog(
  runId: string,
  route: ExecutableRoute,
  events: TelemetryEvent[],
  state: PipelineState,
): string {
  const entries = events.map((event) => createRunLogEntry(event)).join("\n");

  return `# Run Log — ${runId}\n\n## Run Overview\n\n- Mode: dry-run\n- Route: ${route}\n- Status: completed\n- Last completed stage: ${state.last_completed_stage}\n- Next stage: ${state.next_stage}\n\n## Timeline\n\n${entries}\n`;
}

function formatDryRunMetricsSummary(
  runId: string,
  route: ExecutableRoute,
  stageOrder: ReadonlyArray<string>,
): string {
  const durationRows = stageOrder
    .map((stage) => `| ${stage} | 1 | pass |`)
    .join("\n");

  return `# Metrics Summary — ${runId}\n\n## Run\n\n- Mode: dry-run\n- Route: ${route}\n- Final status: completed-pass\n- Stages completed: ${stageOrder.length} of ${stageOrder.length}\n\n## Stage Durations\n\n| Stage | Simulated Phases | Status |\n| ----- | ---------------- | ------ |\n${durationRows}\n`;
}

export function runDryRun(
  input: RunDryRunInput,
  dependencies: RunDryRunDependencies,
): RunDryRunResult {
  const { workspaceRoot, task, route, interactionMode, failurePolicy } = input;
  const runId = dependencies.generateRunId();
  const paths = dependencies.resolveWorkspacePaths(workspaceRoot, runId);
  const stageOrder = getRouteStages(route);
  const state = makeInitialState(runId, {
    mode: "dry-run",
    route,
    total_phases: route === "quick-fix" ? 1 : 0,
    interaction_mode: interactionMode,
    failure_policy: failurePolicy,
  });
  const events: TelemetryEvent[] = [];
  let sequence = 1;

  const pushEvent = (
    eventType: string,
    summary: string,
    overrides: Partial<TelemetryEvent> = {},
  ): void => {
    events.push(
      makeTelemetryEvent(runId, eventType, {
        sequence,
        route,
        summary,
        ...overrides,
      }),
    );
    sequence += 1;
  };

  dependencies.createDirectory(paths.telemetryDir);
  dependencies.writeTextFile(paths.statePath, yamlify(state));
  dependencies.writeTextFile(paths.eventsPath, "");

  pushEvent("run.started", `Dry run started. Route: ${route}.`, {
    payload: { context: { mode: "dry-run" } },
  });

  for (const [index, stage] of stageOrder.entries()) {
    const stageIndex = index + 1;
    const stageId = stageNumber(stage);
    const stageArtifacts = getDryRunStageArtifactPaths(runId, stage);

    pushEvent("stage.started", `Dry run stage ${stageId} (${stage}) started.`, {
      stage: stageId,
      payload: { context: { mode: "dry-run" } },
    });

    for (const artifactPath of stageArtifacts) {
      dependencies.writeTextFile(
        dependencies.resolveWorkspacePath(workspaceRoot, artifactPath),
        createDryRunArtifactContent(
          runId,
          route,
          interactionMode,
          failurePolicy,
          stage,
          task,
          artifactPath,
          stageIndex,
          stageOrder.length,
        ),
      );
    }

    if (stage === "plan") {
      state.total_phases = 1;
    }

    updatePhaseHistory(state, stage);
    state.last_completed_stage = String(stageId);
    const followingStage = nextStage(stage, route);
    state.next_stage =
      followingStage === null ? "done" : String(stageNumber(followingStage));
    state.stages_completed.push(stage);
    dependencies.writeTextFile(paths.statePath, yamlify(state));

    pushEvent(
      "stage.completed",
      `Dry run stage ${stageId} (${stage}) completed.`,
      {
        stage: stageId,
        payload: {
          context: { mode: "dry-run" },
          artifacts: stageArtifacts,
        },
      },
    );
  }

  pushEvent(
    "run.completed",
    `Dry run completed across ${stageOrder.length} stages.`,
    {
      payload: { context: { mode: "dry-run" } },
    },
  );

  dependencies.writeTextFile(
    paths.eventsPath,
    `${events.map((event) => JSON.stringify(event)).join("\n")}\n`,
  );
  dependencies.writeTextFile(
    paths.runLogPath,
    formatDryRunRunLog(runId, route, events, state),
  );
  dependencies.writeTextFile(
    paths.metricsPath,
    formatDryRunMetricsSummary(runId, route, stageOrder),
  );

  return { runId, state };
}
