/**
 * Backward-compatibility re-export shim.
 * All type definitions have moved to src/application/port/index.ts.
 * Import from there for new code; this file exists only for existing flat-module imports.
 */
export type {
  ArtifactId,
  ArtifactRepository,
  BackwardLoopClassification,
  BackwardLoopRequest,
  BuildToolPort,
  Clock,
  DispatchCustomToolCall,
  DispatchRequest,
  DispatchResult,
  DispatchTarget,
  Dispatcher,
  EvidenceQuality,
  ExecOutcome,
  ExplicitRunOptions,
  FailurePolicy,
  GateChoice,
  GateManager,
  GateOption,
  GateRoundDetail,
  GenericCodingTarget,
  IdGenerator,
  InteractionMode,
  LeafAgentDefinition,
  NextStage,
  PhaseHistoryEntry,
  PipelineServices,
  ProgressReporter,
  ResumeSource,
  ReviewState,
  Route,
  RunArtifacts,
  RunState,
  RunStateRepository,
  ShellExecutor,
  SingletonArtifact,
  StageExecutionEnvelope,
  StageModule,
  StageOutcome,
  StageName,
  StageRuntime,
  StageStatus,
  StageTelemetryContext,
  TelemetryEvent,
  TelemetrySink,
  ThinkingLevelName,
  VersionControl,
  VerifyStatus,
} from "./application/port/index.js";
